services:
  web:
    build: 
      context: ./hostel
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./hostel:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  backend:
    build: 
      context: ./hostelServer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./hostelServer:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      